### ISSUE TITLE
Don't force a known hash

### ISSUE THREAD

**Issue by gzip** [gmarty/scumm-nes#11]
Currently if I try to load a rom that has been modified in any way I get an error "Upload one of the ROMs of Maniac Mansion on NES".  Not sure how you want to handle this but one option might be to have a link like "Load anyway" with a select box for the version.

**Comment by gmarty** [comment]
Yes, this is something that I've thought about and I came the same conclusion.
I'd love to avoid using hashes and maybe use some heuristics instead to determine the location of the resources, but not sure if that's really possible.

**Comment by gmarty** [comment]
I implemented a selector for the base rom so that it can be used with ROM hacks in c81fb78.
I still want to use a more solid solution for parsing the different versions, but this is good enough for now.

It unfortunately won't work with complex hacks such as Maniac Mansion Decoded.

**Comment by gzip** [comment]
Just tried it out by applying [this patch](https://github.com/gzip/nes-6502-maniac-mansion-decoded/blob/master/src/patches/coin_box.ips) to the USA version and then with an [old hack](https://www.romhacking.net/hacks/5548/) of the prototype. Works great.
