### ISSUE TITLE
Use correct object initialization states

### ISSUE THREAD

**Issue by gzip** [gmarty/scumm-nes#4]
For example, in room 1 (front of house) the package, film, and tombstones shouldn't be displayed by default. It might be helpful to inspect the initial object states which are stored at `2CA21` in rom, offset by the object id (these get stored in ram starting at `660A`). This is just a nice to have.

**Comment by gmarty** [comment]
Oh nice! I didn't know about that, I thought a script was responsible for that. This is definitely something that's needed.

That's what is referenced as `globdata` in the [resource pointers](https://github.com/gmarty/scumm-nes/blob/main/src/lib/resources.js#L91). So we've got this offset value for all the different versions. The code to parse it on SCUMMVM looks straightforward too.

**Comment by gmarty** [comment]
I implemented it in e27374a.
I figured that bit 0b10000000 (128) was responsible for the initial active or inactive state. The only issue is the cassette tape in room 3 (living room) that is displayed on top of the closed cabinet door.

It's unclear what the other bits are doing. Couldn't find anything in the SCUMMVM codebase. If this is incorrect or incomplete, we can address it in another PR.

Thanks again @gzip for pointing me in the right direction 🎉

**Comment by gzip** [comment]
Here are the notes I have related to the state byte. These deal with the upper 4 bits. I think that high bit is the only one relevant for the tool at the moment. Not sure if the lower 4 bits are actually used, seems like they're always 0xF or 0x0.

`setState08` - triggers the alternate image
`clearState08` - restores original background image
`setState04` - locks the door
`clearState04` - unlocks the door (grate and phone fixed as well)
`setState02` - deactivates the object from mouse
`clearState02` - activates the object for mouse
`setState01` - unknown/unused?
`clearState01` - unknown/unused?
